### ISSUE TITLE
Header moving on tab switch

### ISSUE THREAD

**Issue by misha130** [luap42/codisign#2]
#### Short description of the problem:
When switching tabs the logo moves a few pixels right and left

#### What behavior are you expecting?
The logo to stay at the same location

**Steps to reproduce:**
1. Open home page.
2. Switch to Utilities
3. Switch to Getting Started

https://i.gyazo.com/dd713e1879a0e8dc25d970b4fb69cd49.gif

**Comment by luap42** [comment]
I don't think this is a bug with the framework. When you look at the two pages, you see, that one has a scrollbar, while the other hasn't. The scroll bar changes the screen width, and therefore everything moves a little bit to the left.

I could only imagine the following way to fix this: Force the browser to always show a scroll bar.

However, this looks not so nice on small pages IMO. What do you think?

**Comment by misha130** [comment]
I tested the issue on a another website (SO) and it happens everywhere where you have on the body and not the content so I guess it doesn't matter. Just saw it here because I was looking thoroughly.  
I say either close and forget it or put the scrollbar after the header. I'd rather just close.
